### ISSUE TITLE
Parent stream is closing

### ISSUE THREAD

**Issue by joelamouche** [ssbc/ssb-server#479]
Hi all,

When starting my local server with "sbot server" command, I get this error:
************************************************** (indexes:100%, ebt:100%)Error replicating with @XRg7pXoQqsWDDk4dmgvSWHUqzwS6BmqMo4IdbMKPjWA=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc/stream.js:114:17)
    at /Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc/index.js:45:15
    at remoteCall (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc/api.js:26:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc/api.js:40:20)
    at replicate (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/plugins/replicate/legacy.js:247:13)
    at EventEmitter.fallback (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/plugins/replicate/legacy.js:307:7)
    at Object.onceWrapper (events.js:314:30)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
Error replicating with @L+nPFTMUHWXuchOwuzT6Z8Ea8wD/Rtd7leVRxGaknVk=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc/stream.js:114:17)
    at /Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc/index.js:45:15
    at remoteCall (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc/api.js:26:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc/api.js:40:20)
    at replicate (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/plugins/replicate/legacy.js:247:13)
    at EventEmitter.fallback (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/plugins/replicate/legacy.js:307:7)
    at Object.onceWrapper (events.js:314:30)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)

I was wondering what it meant that my parent stream was closing...

Thanks in advance

**Comment by evbogue** [comment]
I'm also seeing a lot of these messages.

**Comment by cryptix** [comment]
IIRC this is related to ssb-ebbt replication. Looks like it doesn’t close down properly..

**Comment by fczuardi** [comment]
I have this errors when syncing two machines, one running latest scuttlebot on one side and patchwork on the other side.

Before the repeating `parent stream is closing` errors starts, I have some `{message: 'method:ebt,replicate is not on whitelist'}` ones.

**Comment by evbogue** [comment]
@fczuardi Are you also seeing a long sequence of:

```
packet-stream asked to read after closed { value: true, end: false, req: -114 }
packet-stream asked to read after closed { value: true, end: false, req: -105 }
packet-stream asked to read after closed { value: true, end: false, req: -106 }
packet-stream asked to read after closed { value: true, end: false, req: -116 }
packet-stream asked to read after closed { value: true, end: false, req: -108 }
```

As reported here: https://github.com/evbogue/mvd/issues/1

**Comment by fczuardi** [comment]
nope, the sbot logs (logging.level=info) is like this:

```
info @0J0 SBOT 192.168.0.106:8008:@lpzr5GpNv2u/zujQTKXAqJGLNjjip7UGwWujkMwEf+0=.ed25519 PEER JOINED 
Error replicating with @lpzr5GpNv2u/zujQTKXAqJGLNjjip7UGwWujkMwEf+0=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/home/fcz/node9/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/home/fcz/node9/lib/node_modules/scuttlebot/node_modules/muxrpc/stream.js:114:17)
    at /home/fcz/node9/lib/node_modules/scuttlebot/node_modules/muxrpc/index.js:45:15
    at remoteCall (/home/fcz/node9/lib/node_modules/scuttlebot/node_modules/muxrpc/api.js:26:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/home/fcz/node9/lib/node_modules/scuttlebot/node_modules/muxrpc/api.js:40:20)
    at replicate (/home/fcz/node9/lib/node_modules/scuttlebot/plugins/replicate/legacy.js:247:13)
    at EventEmitter.fallback (/home/fcz/node9/lib/node_modules/scuttlebot/plugins/replicate/legacy.js:307:7)
    at Object.onceWrapper (events.js:272:13)
    at EventEmitter.emit (events.js:180:13)
    at /home/fcz/node9/lib/node_modules/scuttlebot/node_modules/ssb-ebt/index.js:109:13
info @0J0 SBOT 192.168.0.106:8008:@lpzr5GpNv2u/zujQTKXAqJGLNjjip7UGwWujkMwEf+0=.ed25519 DISCONNECTED. state was connected for 1.668 seconds 
```

**Comment by christianbundy** [comment]
I *think* I'm getting this error on my Raspberry Pi 3, running Scuttlebot 11.4.2.

```console
$ npm start

> scuttlebot-install@0.0.0 start /home/pi/Source/scuttlebot
> sbot server --host=libra.fraction.io

scuttlebot 11.4.2 /home/pi/.ssb logging.level:notice
my key ID: gTsBPQbdSd763h0qoZsBjPlgWbhKKmMFW8kmTv/XrV8=.ed25519
Error replicating with @AnnTkXjX2LkvuP3IRzd7EtGl2gwEx2lENy74pb1IE90=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/home/pi/Source/scuttlebot/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/home/pi/Source/scuttlebot/node_modules/muxrpc/stream.js:114:17)
    at /home/pi/Source/scuttlebot/node_modules/muxrpc/index.js:45:15
    at remoteCall (/home/pi/Source/scuttlebot/node_modules/muxrpc/api.js:26:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/home/pi/Source/scuttlebot/node_modules/muxrpc/api.js:40:20)
    at replicate (/home/pi/Source/scuttlebot/node_modules/scuttlebot/plugins/replicate/legacy.js:247:13)
    at EventEmitter.fallback (/home/pi/Source/scuttlebot/node_modules/scuttlebot/plugins/replicate/legacy.js:307:7)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at /home/pi/Source/scuttlebot/node_modules/ssb-ebt/index.js:109:13
Error replicating with @AWf8Wn299ZUH7t+JAJL6B217LhDxfHEjgoGOXoYmNjY=.ed25519:
   Error: stream ended with:13 but wanted:34
    at drain (/home/pi/Source/scuttlebot/node_modules/pull-reader/index.js:43:26)
    at /home/pi/Source/scuttlebot/node_modules/pull-reader/index.js:63:18
    at /home/pi/Source/scuttlebot/node_modules/pull-reader/index.js:114:13
    at /home/pi/Source/scuttlebot/node_modules/pull-stream/throughs/through.js:19:9
    at drain (/home/pi/Source/scuttlebot/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/pi/Source/scuttlebot/node_modules/stream-to-pull-stream/index.js:158:5)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! scuttlebot-install@0.0.0 start: `sbot server --host=libra.fraction.io`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the scuttlebot-install@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-08-15T04_21_25_948Z-debug.log
```

Should I open a new issue, or is this the right place for the error?

**Comment by cryptix** [comment]
I think _the parent stream_ is the one giving the error `Error: stream ended with:13 but wanted:34`  but I have no idea why it is closing too soon...

**Comment by romuloalves** [comment]
This is still happening, there is something we can do?

**Comment by christianbundy** [comment]
My intuition here is that this happens when a peer closes the connection abruptly, but if so then this should probably a warning at most. I haven't had time to dig into this yet.
