### ISSUE TITLE
Error on sbot.private.publish (invalid message content, must be object or encrypted string)

### ISSUE THREAD

**Issue by joelamouche** [ssbc/ssb-server#481]
I'm getting an error as callback when calling sbot.private.publish(obj,listOfPeopleInThePrivateChat,cb)
I tried using 'ssb-example-pm' and I got the same error

## listOfPeopleInThePrivateChat
[ '@0hhzPDSecYeruTPKf4lFQVN0k6e0yNOi7MjUf96ieaQ=.ed25519',
  '@0hhzPDSecYeruTPKf4lFQVN0k6e0yNOi7MjUf96ieaQ=.ed25519' ]

## Object passed in the function:

{ type: 'post',
  text: 'okok',
  recps: 
   [ { link: '@0hhzPDSecYeruTPKf4lFQVN0k6e0yNOi7MjUf96ieaQ=.ed25519' },
     { link: '@0hhzPDSecYeruTPKf4lFQVN0k6e0yNOi7MjUf96ieaQ=.ed25519' } ] }

## Error

/Users/antoineestienne/GitFolder/fathom/exploration/test-tech/test-ssb/testPrivateMessage.js:44
						      throw err
						      ^
Error: invalid message content, must be object or encrypted string
    at Object.exports.create (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/ssb-validate/index.js:199:11)
    at /Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/minimal.js:102:17
    at EventEmitter.append (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/minimal.js:88:17)
    at EventEmitter.add (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/secure-scuttlebutt/index.js:89:10)
    at apply (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc-validation/index.js:173:15)
    at EventEmitter.<anonymous> (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc-validation/index.js:82:14)
    at EventEmitter.hooked [as publish] (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/hoox/index.js:10:15)
    at Object.publish (/Users/antoineestienne/.ssb/node_modules/ssb-private/index.js:61:11)
    at Object.hooked (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/hoox/index.js:10:15)
    at Object.localCall (/Users/antoineestienne/.nvm/versions/node/v8.8.0/lib/node_modules/scuttlebot/node_modules/muxrpc/local-api.js:31:31)

**Comment by cryptix** [comment]
Hmm.. Looks okay-ish to me..... [ssb-validate](https://www.npmjs.com/package/ssb-validate) is a new package which got introduced lately after some messages crashed all the sbots...

@dominictarr can you publish the repo? The link on npm returns 404 on github.
