### ISSUE TITLE
sbot blob.get error

### ISSUE THREAD

**Issue by noffle** [ssbc/ssb-server#489]
This particular blob throws this error for me consistently. It was shared with me by another uxer. Other blobs continue to work fine.

```
[~] $ sbot blobs.get '&47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=.sha256'
Exception thrown by PacketStream substream end handler Error: unexpected end of parent stream
    at PacketStream.destroy (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:133:41)
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:58:44
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream-codec/index.js:95:24
    at next (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:14:9)
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:16:41
    at Object.cb (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream-codec/index.js:102:18)
    at drain (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:39:14)
Error: unexpected end of parent stream
    at PacketStream.destroy (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:133:41)
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:58:44
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream-codec/index.js:95:24
    at next (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:14:9)
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:16:41
    at Object.cb (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream-codec/index.js:102:18)
    at drain (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:39:14)
```

**Comment by noffle** [comment]
It seems to be returning now! A friend `sbot blobs.add`ed it via [ssb-webify](https://github.com/noffle/ssb-webify) and I was trying to resolve why their website wasn't loading.

**Comment by dominictarr** [comment]
okay, lets keep an eye on this one

**Comment by christianbundy** [comment]
@noffle Have you noticed any other funky behavior with this blob (or others)?
