### ISSUE TITLE
invite.create fails when `--port` argument used

### ISSUE THREAD

**Issue by rhodey** [ssbc/ssb-server#496]
tested on scuttlebot `11.3.0`, `11.1.1`, and `11.0.0`. logs pasted below are from `11.1.1`. node version `8.11.1`.

## server
```
$ sbot server --port 6666 --host rhodey.org
/home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/plugins/invite.js:111
            cb(null, [addr.host, addr.port, addr.key].join(':') + '~' + seed.toString('base64'))
            ^

TypeError: cb is not a function
    at /home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/plugins/invite.js:111:13
    at /home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/level-sublevel/shell.js:53:51
    at /home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/level-sublevel/nut.js:109:13
```

## client
```
$ sbot --port 6666 invite.create 1
/home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/muxrpcli/index.js:68
      throw err
      ^

Error: unexpected end of parent stream
    at PacketStream.destroy (/home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:133:41)
    at source (/home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:43:24)
    at /home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/pull-goodbye/endable.js:6:7
    at /home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/pull-through/index.js:31:16
    at /home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/pull-through/index.js:31:16
    at source (/home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/pull-pair/index.js:21:7)
    at /home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/pull-cat/index.js:7:11
    at Array.forEach (<anonymous>)
    at abortAll (/home/rhodey/bin/node-v8.11.1-linux-x64/lib/node_modules/scuttlebot/node_modules/pull-cat/index.js:6:7)
```

**Comment by rhodey** [comment]
note, this seems to actually be a separate issue unrelated to issue 390 - [Error when using --port and creating invites > 1](https://github.com/ssbc/scuttlebot/issues/390). If I switch sbot to run on default port and then omit the `--port` argument from the `invite.create` command I can create invites successfully.

**Comment by christianbundy** [comment]
Hey @rhodey, sorry I missed this issue. I'm trying to reproduce your issue but I'm running into https://github.com/ssbc/scuttlebot/issues/583, could you verify that this is still a problem for you on the latest version of Scuttlebot?
