### ISSUE TITLE
Invalid json when loading scuttlebot

### ISSUE THREAD

**Issue by rabble** [ssbc/ssb-server#512]
scuttlebot rabble$ set -e; for t in test/*.js; do node $t; done
...........
TAP version 13
# test invite.accept api
INVITE 192.168.123.119:11962:@2q3at83tsCb/MHxcUU/VcsveiULTzpoxzBcQxnBAxlo=.ed25519~3+mrSJ8cWDgFIvCGrGNau7k4rTlQR+6+axNiRm4FYwk=
undefined:7
  {
  ^

SyntaxError: Unexpected token { in JSON at position 89
    at JSON.parse (<anonymous>)
    at exports.parse (/Users/rabble/code/ssb/scuttlebot/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/Users/rabble/code/ssb/scuttlebot/node_modules/rc/index.js:30:20)
    at Array.forEach (<anonymous>)
    at module.exports (/Users/rabble/code/ssb/scuttlebot/node_modules/rc/index.js:43:36)
    at module.exports (/Users/rabble/code/ssb/scuttlebot/node_modules/ssb-config/inject.js:15:10)
    at module.exports (/Users/rabble/code/ssb/scuttlebot/node_modules/ssb-client/index.js:44:14)
    at connect (/Users/rabble/code/ssb/scuttlebot/plugins/invite.js:189:11)
    at next (/Users/rabble/code/ssb/scuttlebot/plugins/invite.js:205:13)
    at retry (/Users/rabble/code/ssb/scuttlebot/plugins/invite.js:211:13)
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...19 completed.

I have no idea what json is failing. How do i debug this? It's killing patchwork, patchbay, and sbot. Thoughts? I'd ask on scuttlebutt but this has me locked out.

**Comment by dominictarr** [comment]
that stacktrace is coming from `rc` which is the configuration loader. I'd say your config file `~/.ssb/config` has invalid json, but it _shouldn't_ being touched to run the tests. hmm, but I just tested that and I saw it does seem to look in that directory! this is definitely a bug. Maybe check that you do have valid json at `~/.ssb/config`?
