### ISSUE TITLE
getAddress errors on scuttlebot@12

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-server#541]
when running the latest version, getAddress just errors:

```
]$ sbot getAddress
/home/dominic/.nvm/versions/node/v8.11.4/lib/node_modules/scuttlebot/node_modules/muxrpcli/index.js:68
      throw err
      ^

Error: unexpected end of parent stream
    at PacketStream.destroy (/home/dominic/.nvm/versions/node/v8.11.4/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:71:7)
    at PacketStream.write (/home/dominic/.nvm/versions/node/v8.11.4/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:133:41)
    at /home/dominic/.nvm/versions/node/v8.11.4/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:58:44
    at /home/dominic/.nvm/versions/node/v8.11.4/lib/node_modules/scuttlebot/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/dominic/.nvm/versions/node/v8.11.4/lib/node_modules/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/dominic/.nvm/versions/node/v8.11.4/lib/node_modules/scuttlebot/node_modules/packet-stream-codec/index.js:95:24
    at next (/home/dominic/.nvm/versions/node/v8.11.4/lib/node_modules/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:14:9)
    at /home/dominic/.nvm/versions/node/v8.11.4/lib/node_modules/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:16:41
    at Object.cb (/home/dominic/.nvm/versions/node/v8.11.4/lib/node_modules/scuttlebot/node_modules/packet-stream-codec/index.js:102:18)
    at drain (/home/dominic/.nvm/versions/node/v8.11.4/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:39:14)

```

**Comment by arj03** [comment]
That seems like a bug. If I have an incoming connections config defined with external, it seems to work though. I wonder why tests didn't pick this up. Will see what I can find.

**Comment by arj03** [comment]
@dominictarr its a wierd bug in muxrpc somewhere, where it gets an empty string from multiserver / secret-stack and then just blows up. I'm not familiar with that part of the stack. `sbot getAddress private` works because private scope is defined by default.

**Comment by arj03** [comment]
Hmm this is a bit of a mess, as it also hits [invites](https://github.com/ssbc/scuttlebot/issues/540). I'm tempted to do a new version of ssb-config where net is public by default instead of private. Also I'll add a section to the release notes explaining what this means for invites.

**Comment by arj03** [comment]
Published ssb-config with the scope change and scuttlebot 12.0.1 which make it easier to create invites similar to the old model.
