### ISSUE TITLE
Better error messages when creating invites

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-server#553]
I could've sworn the usage was `sbot invite.create 1 --external example.com`, but when I run that I get:

```

/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/muxrpcli/index.js:68
      throw err
      ^
TypeError: cb is not a function
    at Object.<anonymous> (/home/christianbundy/src/patchbay/node_modules/scuttlebot/plugins/invite.js:84:18)
    at apply (/home/christianbundy/src/patchbay/node_modules/muxrpc-validation/index.js:175:15)
    at Object.<anonymous> (/home/christianbundy/src/patchbay/node_modules/muxrpc-validation/index.js:82:14)
    at Object.hooked (/home/christianbundy/src/patchbay/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/christianbundy/src/patchbay/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/home/christianbundy/src/patchbay/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/home/christianbundy/src/patchbay/node_modules/muxrpc/stream.js:46:17)
    at PacketStream._onrequest (/home/christianbundy/src/patchbay/node_modules/packet-stream/index.js:161:17)
    at PacketStream.write (/home/christianbundy/src/patchbay/node_modules/packet-stream/index.js:134:41)
    at /home/christianbundy/src/patchbay/node_modules/muxrpc/pull-weird.js:56:15
```

It turns out that when specifying a number you have to use the `-n` or `--n` flag, which seems like it would be *very* helpful for new users. 

SSB context: `%9QMA4+JLF2oemPYYBnw6oFDDUov3nZZ1VCAtAbLtn08=.sha256`

**Comment by sganz** [comment]
Also seems to work with this Format.
> sbot invite.create --uses 5 --external my-pub.com

Also when invalid invite command are given it will often cause the sbot server to throw an exception and die.

@christianbundy  Thanks again!

**Comment by cryptix** [comment]
> Also when invalid invite command are given it will often cause the sbot server to throw an exception and die.

Every one of those would be a valid bug report IMHO. If you can give us the stack traces of the crashs this shouldn’t be to hard to get to the root of.

**Comment by sganz** [comment]
Started sbot server with this command

> sbot server --host scuttlebot.me --allowPrivate --logging.level info

And then the Invite on a different session which causes the server to toss.

> sbot invite.create --external scuttlebot.me 1

Error from the sbot server console

>TypeError: cb is not a function
at /usr/local/lib/node_modules/scuttlebot/plugins/invite.js:117:13
at /usr/local/lib/node_modules/scuttlebot/node_modules/level-sublevel/shell.js:53:51
at /usr/local/lib/node_modules/scuttlebot/node_modules/level-sublevel/nut.js:109:13
scuttlebot 12.2.3 /home/ubuntu/.ssb logging.level:info

On the console  where sbot is trying to issuing the invite (looks like it lost the connection due to dead server)

>Error: unexpected end of parent stream
at PacketStream.destroy (/usr/local/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:71:7) ...

Hope this helps

Sandy

**Comment by sganz** [comment]
@cryptix If you have not set up an AWS Free tier it's an easy way to test. 

Might be issue related to allowPrivate but not sure, but might also be related to parameter passing/use when it's totally out of whack  (technical term) since the way that I had tried the create invite was not right.

**Comment by sganz** [comment]
@cryptix If you have not set up an AWS Free tier it's an easy way to test. 

Might be issue related to allowPrivate but not sure, but might also be related to parameter passing/use when it's totally out of whack  (technical term) since the way that I had tried the create invite was not right.

**Comment by christianbundy** [comment]
I'm using all vanilla everything and this command still throws the "cb is not a function":

```console
$ sbot invite.create 1 --external example.com

/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/muxrpcli/index.js:68
      throw err
      ^
TypeError: cb is not a function
    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchbay/node_modules/scuttlebot/plugins/invite.js:87:18)
    at apply (/home/christianbundy/src/ssbc/patchbay/node_modules/muxrpc-validation/index.js:175:15)
    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchbay/node_modules/muxrpc-validation/index.js:82:14)
    at Object.hooked (/home/christianbundy/src/ssbc/patchbay/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/christianbundy/src/ssbc/patchbay/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/home/christianbundy/src/ssbc/patchbay/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/home/christianbundy/src/ssbc/patchbay/node_modules/muxrpc/stream.js:46:17)
    at PacketStream._onrequest (/home/christianbundy/src/ssbc/patchbay/node_modules/packet-stream/index.js:161:17)
    at PacketStream.write (/home/christianbundy/src/ssbc/patchbay/node_modules/packet-stream/index.js:134:41)
    at /home/christianbundy/src/ssbc/patchbay/node_modules/muxrpc/pull-weird.js:56:15
```
