### ISSUE TITLE
scuttlebot 13.0.x hangs on ipv6 addresses

### ISSUE THREAD

**Issue by myf** [ssbc/ssb-server#571]
serving `sbot server` with an option of `--host=[ipv6_address]` will result in the sbot instance never finish up syncing, leaving cpu running at 100%.

**Comment by christianbundy** [comment]
Could you clarify which version of sbot you're using? I'm also running cjdns, and this works fine for me on sbot 13.0.3:

```console
$ sbot server --host 'fce2:9811:4862:81a7:bb08:91d6:2e41:d220'
scuttlebot 13.0.3 /home/christianbundy/.ssb logging.level:notice
my key ID: +oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519
ssb-friends: stream legacy api used
Trace: deprecated api used: ssb-ref.parseAddress
    at Object.parseAddress (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/ssb-ref/index.js:96:15)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/plugins/local.js:55:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/broadcast-stream/index.js:51:12)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
Trace: deprecated api used: ssb-ref.parseMultiServerAddress
    at /home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/ssb-ref/index.js:96:15
    at Object.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/ssb-ref/index.js:191:14)
    at Object.parseAddress (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/ssb-ref/index.js:99:15)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/plugins/local.js:55:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/scuttlebot/node_modules/broadcast-stream/index.js:51:12)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
************************************************** ()
```

On the other hand, I've tried using `--host=asdfasdjf` and it doesn't change the output, so maybe I'm not actually hosting on that address? This *must* be documented somewhere, but I though we switched from `--host` to `--external` back at sbot@12.0.0. Or maybe that's just for invites? :confused: 

What does your `~/.ssb/config` look like? Based on [these docs](https://github.com/ssbc/ssb-config#connections) I think you need to set your IPv6 address there rather than use a CLI flag, but again I'm really not sure.

cc: @arj03 @cryptix

**Comment by myf** [comment]
@christianbundy i am indeed running `13.0.3` as well

**Comment by myf** [comment]
change from `--host=[ipv6_address]` to `--host 'ipv6_address' somehow works. i guess there's some change in the config? will do it properly

**Comment by myf** [comment]
it's not that simple... it still hangs sometimes, i could not replicate it every time though.

**Comment by dominictarr** [comment]
ipv6 support is _quite_ difficult to test, because of the various compatibility layers. you might have a local ipv6 address, but you don't really have ipv6 support on your network etc.

To confirm: you are hosting from your home computer using cjdns - and then clients connect to it and the server hangs? or is it your server connecting as the client to other cjdns peers?
