### ISSUE TITLE
WebSocket test failing in test/bin.js

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-server#576]
This test has been failing for me for the past few days, the failure is [here](https://github.com/ssbc/scuttlebot/blob/0ad34acfc4e5be6b6b5b07d4490ae8ca306cc32a/test/bin.js#L215):

```
# result of sbot getAddress: net:127.0.0.1:9001~shs:nh3oO007Sh7GHV72MP+h8ntadP8CMFco8ygAtqQwaQo=
not ok 6 has one ws remote
  ---
    operator: equal
    expected: 1
    actual:   0
    at: <anonymous> (/home/christianbundy/src/ssbc/scuttlebot/test/bin.js:215:7)
    stack: |-
      Error: has one ws remote
          at Test.assert [as _assert] (/home/christianbundy/src/ssbc/scuttlebot/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/christianbundy/src/ssbc/scuttlebot/node_modules/tape/lib/test.js:76:32)
          at Test.equal (/home/christianbundy/src/ssbc/scuttlebot/node_modules/tape/lib/test.js:384:10)
          at Test.bound [as equal] (/home/christianbundy/src/ssbc/scuttlebot/node_modules/tape/lib/test.js:76:32)
          at /home/christianbundy/src/ssbc/scuttlebot/test/bin.js:215:7
          at /home/christianbundy/src/ssbc/scuttlebot/test/bin.js:62:24
          at /home/christianbundy/src/ssbc/scuttlebot/test/bin.js:202:7
          at ChildProcess.exithandler (child_process.js:268:7)
          at emitTwo (events.js:126:13)
          at ChildProcess.emit (events.js:214:7)
  ...
/home/christianbundy/src/ssbc/scuttlebot/node_modules/multiserver-address/index.js:18
    return e.map(function (e) {
             ^

TypeError: Cannot read property 'map' of undefined
    at /home/christianbundy/src/ssbc/scuttlebot/node_modules/multiserver-address/index.js:18:14
    at Array.map (<anonymous>)
    at Object.exports.encode (/home/christianbundy/src/ssbc/scuttlebot/node_modules/multiserver-address/index.js:17:15)
    at /home/christianbundy/src/ssbc/scuttlebot/test/bin.js:216:21
    at /home/christianbundy/src/ssbc/scuttlebot/test/bin.js:62:24
    at /home/christianbundy/src/ssbc/scuttlebot/test/bin.js:202:7
    at ChildProcess.exithandler (child_process.js:268:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
killing sbot
```

cc: @regular

**Comment by regular** [comment]
@christianbundy the immediate cause seems to be a missing sanity check here: https://github.com/dominictarr/multiserver-address/blob/master/index.js#L17

... but the real cause is probably something else. @dominictarr do you have a clue?

**Comment by dominictarr** [comment]
this passes for me, do you have these deps:

```
$ npm ls ssb-ws multiserver secret-stack
scuttlebot@13.1.0 /home/dominic/c/scuttlebot
+-- multiserver@3.0.2 
+-- secret-stack@5.0.0 
| `-- multiserver@3.0.2  deduped
+-- ssb-client@4.6.0
| `-- multiserver@1.13.7 
`-- ssb-ws@5.1.1 
  `-- multiserver@3.0.2  deduped
```

**Comment by christianbundy** [comment]
@dominictarr 

Nope, looks like I'm behind.

```console
$ npm ls ssb-ws multiserver secret-stack
scuttlebot@13.0.3 /home/christianbundy/src/ssbc/scuttlebot
├── multiserver@2.0.0 
├─┬ secret-stack@4.2.4 
│ └── multiserver@1.13.7 
├─┬ ssb-client@4.6.0
│ └── multiserver@1.13.7 
└─┬ ssb-ws@3.0.2 
  └── multiserver@1.13.7 
```

I pushed my full dependency tree as a lockfile in c98e2f8f6599dab5024f4d0f0656b7a41d2f450f, if you checkout the branch and run `npm ci` you should be able to reproduce my exact setup. I'll try pulling from master and reinstallin to try to sync up our dependency trees again.
