### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined (ssb-friends)

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-server#608]
```console
$ ssb-server start
ssb-server 13.5.2 /home/christianbundy/.ssb logging.level:notice
my key ID: +oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519
WARNING-DEPRECATION: ssb-links not installed as a plugin. If you are using git-ssb, ssb-npm or patchfoo please consider installing it
Listening on undefined:8008 (multiserver net plugin)
Listening on :8989 (multiserver ws plugin)
ssb-friends: stream legacy api used
Trace: deprecated api used: ssb-ref.parseAddress
    at Object.parseAddress (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-ref/index.js:96:15)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/plugins/local.js:55:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/broadcast-stream/index.js:51:12)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-friends/index.js:56
        if(g && opts.id !== id && g[opts.id] && g[opts.id][id] === -1) {
                     ^

TypeError: Cannot read property 'id' of undefined
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-friends/index.js:56:22
    at Object.onReady (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/layered-graph/index.js:81:22)
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-friends/index.js:54:15
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-cont/source.js:18:5
    at next (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-stream/sinks/drain.js:16:11)
    at sink (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-stream/sinks/drain.js:37:9)
    at sink (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:61:7)
    at Object.exports.pipeToStream (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/muxrpc/util.js:138:5)
    at PacketStreamSubstream.stream.read (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/muxrpc/stream.js:76:18)
    at PacketStream._onstream (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:228:11)
```

```console
$ ssb-server createHistoryStream
Exception thrown by PacketStream substream end handler Error: stream ended with:0 but wanted:34
    at drain (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:43:26)
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:63:18
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:114:13
    at drain (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/stream-to-pull-stream/index.js:158:5)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Error: stream ended with:0 but wanted:34
    at drain (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:43:26)
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:63:18
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:114:13
    at drain (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/stream-to-pull-stream/index.js:158:5)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by christianbundy** [comment]
No `~/.ssb/config`, all vanilla everything.

**Comment by dominictarr** [comment]
it doesn't make sense to call createHistoryStream without any options, but since ssb-db allows it just fall though to there. fixed in 3.1.11

**Comment by christianbundy** [comment]
Oops. I always get `createHistoryStream` and `createFeedStream` mixed up. Is there any context that might make this more intuitive for me? In my mind "feed" makes me think of a single Scuttlebutt feed and "history" gives me the impression of being many feeds, but I know that's wrong.

**Comment by dominictarr** [comment]
Yeah, this is a historical quirk now. We can't change it because it would break legacy replication (well, we could change createFeedStream, does any UI client actually use that?) I normally do my testing with `createLogStream`

**Comment by christianbundy** [comment]
Cool, I'll try to just remember `createLogStream`. Also, FWIW, it looks like it's used a few times but not a ton:

```console
$ grep -r 'createFeedStream(' | grep -v node_modules
ssb-threads/index.ts:        ssb.createFeedStream({ reverse: false, old: false, live: true }),
git-ssb-patchfoo/lib/app.js:      this.sbot.createFeedStream({
git-ssb-patchfoo/lib/app.js:    ? this.createFeedStream(opts)
git-ssb-patchfoo/lib/app.js:    this.sbot.createFeedStream(opts),
ssb-git-repo/index.js:    sbot.createFeedStream(options),
ssb-feed/test/validation.js:                  ssb.createFeedStream({ keys: false }),
ssb-feed/test/feed.js:          ssb.createFeedStream(),
ssb-feed/test/feed.js:          ssb.createFeedStream({ live: true }),
ssb-feed/test/feed.js:          ssb.createFeedStream({ live: true }),
ssb-testing-guide/basic/ex3/index.test.js:      server.createFeedStream(),
ssb-testing-guide/basic/ex2/index.test.js:    server.createFeedStream({ live: true }),
scuttlebot.io/tmpl/apis/scuttlebot/ssb.md:createFeedStream({
scuttlebot.io/tmpl/docs/advanced/feed-send-time-sort.md:  sbot.createFeedStream({ reverse: true }),
ssb-usage-stats/active-daily.js:    ssb.createFeedStream(),
patchwork/modules/sbot.js:            sbot.createFeedStream(opts),
patchwork/sbot/private-feed.js:        ssb.createFeedStream({
patchwork/sbot/public-feed.js:        ssb.createFeedStream({ live: true, old: false, awaitReady: false }),
patchwork/sbot/public-feed.js:          cb(null, pullResume.source(ssb.createFeedStream(opts), {
patchwork/sbot/participating-feed.js:        ssb.createFeedStream({ live: true, old: false }),
patchwork/sbot/participating-feed.js:      return pullResume.source(ssb.createFeedStream(opts), {
patchwork/sbot/recent-feeds.js:          sbot.createFeedStream({ reverse: true, gt: since }),
patchwork/sbot/recent-feeds.js:          sbot.createFeedStream({ old: false }),
patchwork/sbot/network-feed.js:        ssb.createFeedStream({ live: true, old: false }),
patchwork/sbot/network-feed.js:      return pullResume.source(ssb.createFeedStream(opts), {
patchcore/sbot.js:            sbot.createFeedStream(opts),
patchfoo/lib/app.js:      this.sbot.createFeedStream({
patchfoo/lib/app.js:    ? this.createFeedStream(opts)
patchfoo/lib/app.js:    this.sbot.createFeedStream(opts),
ssb-server/README.md:    ssbServer.createFeedStream(),
ssb-server/api.md:createFeedStream({ live:, gt:, gte:, lt:, lte:, reverse:, keys:, values:, limit:, fillCache:, keyEncoding:, valueEncoding: })
ssb-db/README.md:  ssb.createFeedStream(),
ssb-db/test/validation.js:                  ssb.createFeedStream({ keys: false }),
ssb-db/test/validation.js:                  ssb.createFeedStream({ keys: false }),
ssb-db/test/feed.js:        ssb.createFeedStream(),
ssb-db/test/feed.js:        ssb.createFeedStream({ tail: true }),
ssb-db/test/feed.js:        ssb.createFeedStream({ tail: true }),
ssb-db/test/feed.js:        ssb.createFeedStream({ values: false }),
ssb-db/test/feed.js:        ssb.createFeedStream({ keys: false }),
ssb-db/test/msg-encoding.js:        ssb.createFeedStream(),
patchwork-builder/app/modules/sbot.js:            sbot.createFeedStream(opts),
patchwork-builder/app/sbot/public-feed.js:          ssb.createFeedStream({ live: true, old: false }),
patchwork-builder/app/sbot/public-feed.js:        stream.resolve(pullResume.source(ssb.createFeedStream(opts), {
patchwork-builder/app/sbot/recent-feeds.js:          sbot.createFeedStream({ reverse: true, gt: since }),
patchwork-builder/app/sbot/recent-feeds.js:          sbot.createFeedStream({ old: false }),
patchwork-builder/app/sbot/network-feed.js:        ssb.createFeedStream({ live: true, old: false }),
patchwork-builder/app/sbot/network-feed.js:        stream.resolve(pullResume.source(ssb.createFeedStream(opts), {
