### ISSUE TITLE
tests failing on master `tests/bin.js`

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-server#614]
**NOTE** - i've disabled the tests before this (lines 135-225) as this test is slow. I'ts like 30s running this, and longer when running it all. The output for this part is that same though

trace : 
```bash
mixmix SSBC/ssb-server ‹master*› » node test/bin.js

TAP version 13
# ssb-server client should work without options
ssb-server 13.6.0 /tmp/ssb-server_binjstest_1547448035205 logging.level:notice
my key ID: DJMtxaXLtuzHYzOgAgGB9fd4EILQxplDNlXhfqk41ms=.ed25519
WARNING-DEPRECATION: ssb-links not installed as a plugin. If you are using git-ssb, ssb-npm or patchfoo please consider installing it
Listening on 2407:7000:9c49:4e00:f85b:561c:f34:aac7:43293 (multiserver net plugin)
Listening on :43294 (multiserver ws plugin)
ssb-friends: stream legacy api used
try more: 10
retry run 10
work(err): { Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=' }
try more: 9
retry run 9
work(err): { Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=' }
try more: 8
retry run 8
work(err): { Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=' }
try more: 7
retry run 7
work(err): { Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=' }
try more: 6
retry run 6
work(err): { Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=' }
try more: 5
retry run 5
work(err): { Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=' }
try more: 4
retry run 4
work(err): { Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=' }
try more: 3
retry run 3
work(err): { Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=' }
try more: 2
retry run 2
work(err): { Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=' }
try more: 1
retry run 1
work(err): { Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=' }
try more: 0
not ok 1 ssb-server getAddress succeeds eventually
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { [Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.
] killed: false, code: 1, signal: null, cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=' }
    at: <anonymous> (/home/mix/projects/SSBC/ssb-server/test/bin.js:260:7)
    stack: |-
      Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547448035205 --config /tmp/ssb-server_binjstest_1547448035205/config --caps.shs J5puM7zxpHe86j3qOUgU5iY04g9MOxo2vODvbhZi0vc=
      Error: Could not connect to ssb-server localhost:43293
      Use the "start" command to start it.
      
          at ChildProcess.exithandler (child_process.js:275:12)
          at emitTwo (events.js:126:13)
          at ChildProcess.emit (events.js:214:7)
          at maybeClose (internal/child_process.js:925:16)
          at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  ...
ok 2 should be equal

1..2
# tests 2
# pass  1
# fail  1
```

cc @dominictarr

**Comment by dominictarr** [comment]
hmm, how come it says:

```
Listening on 2407:7000:9c49:4e00:f85b:561c:f34:aac7:43293 (multiserver net plugin)
Listening on :43294 (multiserver ws plugin)
```
why does it use ipv6 there? for net but not multiserver? If this is a ipv6 thing that would certainly explain why it might work for one person (me) but not you.

Anyway, to rule out deps, I pushed a package-lock that works for me to the `passing` branch.
(and also enabled `--verbose` option in that test, so that we can see the actual error by which it didn't connect)

**Comment by dominictarr** [comment]
for me it says

```
Listening on undefined:43293 (multiserver net plugin)
Listening on :43294 (multiserver ws plugin)
```
@mixmix do the multiserver tests pass for you?

**Comment by mixmix** [comment]
checkout out `passing` branch, nuked node_modules and installed

ran with node v8.11.3 , npm 6.5.0

Here's the tail of the tests (prior to this there's try more 10 ... 1 counting down)

```bash
try more: 0
not ok 43 ssb-server getAddress succeeds eventually
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { [Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547449356370 --config /tmp/ssb-server_binjstest_1547449356370/config --caps.shs KxaCbiQ2G8K7gC+c8F0WcIyrhz9cmMRux91mkLIky/I= --verbose
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.
/home/mix/projects/SSBC/ssb-server/bin.js:112
        if(config.verbose) throw err
                           ^

Error: could not connect to sbot
    at /home/mix/projects/SSBC/ssb-server/node_modules/ssb-client/index.js:100:23
    at /home/mix/projects/SSBC/ssb-server/node_modules/ssb-client/node_modules/multiserver/compose.js:66:24
    at Socket.<anonymous> (/home/mix/projects/SSBC/ssb-server/node_modules/ssb-client/node_modules/multiserver/plugins/net.js:42:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  Error: connect ECONNREFUSED 127.0.0.1:43293
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
] killed: false, code: 1, signal: null, cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547449356370 --config /tmp/ssb-server_binjstest_1547449356370/config --caps.shs KxaCbiQ2G8K7gC+c8F0WcIyrhz9cmMRux91mkLIky/I= --verbose' }
    at: <anonymous> (/home/mix/projects/SSBC/ssb-server/test/bin.js:258:7)
    stack: |-
      Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547449356370 --config /tmp/ssb-server_binjstest_1547449356370/config --caps.shs KxaCbiQ2G8K7gC+c8F0WcIyrhz9cmMRux91mkLIky/I= --verbose
      Error: Could not connect to ssb-server localhost:43293
      Use the "start" command to start it.
      /home/mix/projects/SSBC/ssb-server/bin.js:112
              if(config.verbose) throw err
                                 ^
      
      Error: could not connect to sbot
          at /home/mix/projects/SSBC/ssb-server/node_modules/ssb-client/index.js:100:23
          at /home/mix/projects/SSBC/ssb-server/node_modules/ssb-client/node_modules/multiserver/compose.js:66:24
          at Socket.<anonymous> (/home/mix/projects/SSBC/ssb-server/node_modules/ssb-client/node_modules/multiserver/plugins/net.js:42:11)
          at emitOne (events.js:116:13)
          at Socket.emit (events.js:211:7)
          at emitErrorNT (internal/streams/destroy.js:64:8)
          at _combinedTickCallback (internal/process/next_tick.js:138:11)
          at process._tickCallback (internal/process/next_tick.js:180:9)
        Error: connect ECONNREFUSED 127.0.0.1:43293
          at Object._errnoException (util.js:992:11)
          at _exceptionWithHostPort (util.js:1014:20)
          at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
      
          at ChildProcess.exithandler (child_process.js:275:12)
          at emitTwo (events.js:126:13)
          at ChildProcess.emit (events.js:214:7)
          at maybeClose (internal/child_process.js:925:16)
          at Socket.stream.socket.on (internal/child_process.js:346:11)
          at emitOne (events.js:116:13)
          at Socket.emit (events.js:211:7)
          at Pipe._handle.close [as _onclose] (net.js:557:12)
  ...
ok 44 should be equal

1..44
# tests 44
# pass  43
# fail  1
```

**Comment by mixmix** [comment]
commenting out the `--verbose` line I get the same error as earlier @dominictarr 

```bash
try more: 0
not ok 43 ssb-server getAddress succeeds eventually
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { [Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547449580634 --config /tmp/ssb-server_binjstest_1547449580634/config --caps.shs 65aZnFhtXMvAA4fD03jkAf5QL7+h+GgPbvUIsDRSrhI=
Error: Could not connect to ssb-server localhost:43293
Use the "start" command to start it.
] killed: false, code: 1, signal: null, cmd: '/home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547449580634 --config /tmp/ssb-server_binjstest_1547449580634/config --caps.shs 65aZnFhtXMvAA4fD03jkAf5QL7+h+GgPbvUIsDRSrhI=' }
    at: <anonymous> (/home/mix/projects/SSBC/ssb-server/test/bin.js:258:7)
    stack: |-
      Error: Command failed: /home/mix/projects/SSBC/ssb-server/bin.js getAddress device --path /tmp/ssb-server_binjstest_1547449580634 --config /tmp/ssb-server_binjstest_1547449580634/config --caps.shs 65aZnFhtXMvAA4fD03jkAf5QL7+h+GgPbvUIsDRSrhI=
      Error: Could not connect to ssb-server localhost:43293
      Use the "start" command to start it.
      
          at ChildProcess.exithandler (child_process.js:275:12)
          at emitTwo (events.js:126:13)
          at ChildProcess.emit (events.js:214:7)
          at maybeClose (internal/child_process.js:925:16)
          at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  ...
ok 44 should be equal

1..44
# tests 44
# pass  43
# fail  1


```

**Comment by dominictarr** [comment]
```
  Error: connect ECONNREFUSED 127.0.0.1:43293
```
what does it say at "listening on" ...??? (multiserver net plugin) I'm guessing an ipv6 thing?

`--verbose` just enables this line: https://github.com/ssbc/ssb-server/blob/master/bin.js#L112 otherwise the real error is hidden.

**Comment by mixmix** [comment]
yeah I figured the verbose throw as I posted it :P 

Here's the bit at the top of the 43'rd test : 

```bash
# ssb-server client should work without options
ssb-server 13.6.0 /tmp/ssb-server_binjstest_1547449580634 logging.level:notice
my key ID: pxwkgikCsfui1cKj0NrD4dRZQsoWOdgUUL1yA6WKFv0=.ed25519
WARNING-DEPRECATION: ssb-links not installed as a plugin. If you are using git-ssb, ssb-npm or patchfoo please consider installing it
Listening on 2407:7000:9c49:4e00:f85b:561c:f34:aac7:43293 (multiserver net plugin)
Listening on :43294 (multiserver ws plugin)
ssb-friends: stream legacy api used
try more: 10
retry run 10

```

**Comment by dominictarr** [comment]
hmm, why is it doing that?

incidentially it passes on travis. (where ipv6 is disabled)

**Comment by dominictarr** [comment]
this line: https://github.com/ssbc/multiserver/blob/master/plugins/net.js#L24

**Comment by mixmix** [comment]
I've heard a couple of people saying the command line sbot thing is broken for them at the moment. Could be related, or could be the same thing. There's also something about the current sbot which doesn't play well with git-ssb. Just naming smells I've caught recently

**Comment by mixmix** [comment]
```bash
mixmix SSBC/ssb-server ‹passing*› » node                                                                                                                                                                                                   1 ↵
> require('multiserver-scopes').host('public')
'2407:7000:9c49:4e00:f85b:561c:f34:aac7'

```

**Comment by dominictarr** [comment]
well, the good news is that you should be able to receive direct p2p tcp connections quite easily since you seem to have an externally facing ipv6 address.

**Comment by mixmix** [comment]
I've npm linked that branch of ssb-config to `ssb-server#passing`. Tests pass, but there are less of them (because less repeat try i guess)

```bash
1..29
# tests 29
# pass  29

# ok

```


I'm confused

**Comment by mixmix** [comment]
awesome, this'll probably fix things for matt which will mean he can actually publish patches :D

**Comment by dominictarr** [comment]
the repeat try doesn't count as a test, it's just to handle the indeterminacy
