### ISSUE TITLE
sbot publish "cb is not a function"

### ISSUE THREAD

**Issue by qypea** [ssbc/ssb-server#616]
Resetting my pub today with a new identity(forked feed during a crash a while back) I can't seem to set its identity:
```
+ sbot publish --type about --about @7NywnCEShB7wv7xEqqPJ4wxguoZuRQ2KhBv9Fvr1lMM=.ed25519 --name qypea1.dyndns.info --description 'Public Pub run by @PZjQKGbh9KrWHAp1lo9nH/WXqGLp5rpqpVYLccJLkE4=.ed25519.'

/home/pi/ssb-server/node_modules/muxrpcli/index.js:68
      throw err
      ^
TypeError: cb is not a function
    at /home/pi/ssb-server/node_modules/ssb-db/minimal.js:201:7
    at EventEmitter.append (/home/pi/ssb-server/node_modules/ssb-db/minimal.js:162:18)
    at Object.add (/home/pi/ssb-server/node_modules/ssb-db/index.js:97:10)
    at apply (/home/pi/ssb-server/node_modules/muxrpc-validation/index.js:178:13)
    at Object.<anonymous> (/home/pi/ssb-server/node_modules/muxrpc-validation/index.js:82:14)
    at Object.hooked (/home/pi/ssb-server/node_modules/hoox/index.js:10:15)
    at Object.localCall (/home/pi/ssb-server/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/home/pi/ssb-server/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/home/pi/ssb-server/node_modules/muxrpc/stream.js:48:17)
    at PacketStream._onrequest (/home/pi/ssb-server/node_modules/packet-stream/index.js:161:17)
```

This happens on current master(a02929065bd72c36a2448d9329add73a42d7e8be), v13.5.0, v13.6.1

**Comment by qypea** [comment]
Seems likely to be an instance of #507

**Comment by black-puppydog** [comment]
FWIW, I'm getting this following along with @ahdinosaur's new [ssb-pub tutorial](https://github.com/ahdinosaur/ssb-pub#manual-setup) (manual setup, and with a separate user in the root group)

**Comment by dominictarr** [comment]
this will be fixed by: https://github.com/ssbc/ssb-server/pull/652

**Comment by dominictarr** [comment]
this should be fixed now

**Comment by samuk** [comment]
I ran into this today. Any idea why it's reappeared? 
This is what I've done
https://github.com/Agroecology-Lab/edu-hotspot/blob/master/README.md#to-do
