### ISSUE TITLE
ssb-server get --private: cb is not a function

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-server#620]
Probably related to #616, but `ssb-server get $msg --private` is throwing the following:

```console
$ ssb-server get --private=true  %90awctn3YKZaod4teIGaNcRlvV5HHC8khb0aB6I2koU=.sha256

/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:68
      throw err
      ^
TypeError: cb is not a function
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-ooo/index.js:95:20
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-db/index.js:68:9
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumeview-hashtable/index.js:99:11
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumeview-hashtable/multi.js:33:21
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumeview-hashtable/hashtable.js:50:17
    at Array.unboxerMap (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-db/minimal.js:85:35)
    at chainMaps (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-db/minimal.js:90:14)
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumedb/index.js:71:14
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumelog-offset/inject.js:76:14
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:48:11
```

Does `--private` work for anyone? I'm not sure when or why this changed, but I'm seeing it on both v13 and v14.

**Comment by dominictarr** [comment]
it should be: `sbot get --private=true --id  %90awctn3YKZaod4teIGaNcRlvV5HHC8khb0aB6I2koU=.sha256`
so that it becomes `sbot.get({private:true, id:...}, cb)` maybe the way you did it, it becomes `sbot.get(id, {private: true}, cb)` that's too many signatures

**Comment by dominictarr** [comment]
(not actually sure if it does that, just guessing)

**Comment by dominictarr** [comment]
muxrpcli only allows one argument. `<message_id> --private` becomes `(message_id, {private: true})`

hmm a better way to handle defaults like that, is to always map the default positional arg to an option. then `message_id --private` would become `{id, private}` which is much easier to handle programatically. Since working on https://github.com/ssbc/ssb-server/pull/652 I think we should just deprecate positional calls, makes documenting all the ways to call a thing a bit awkward

**Comment by dominictarr** [comment]
this should be fixed now!

**Comment by christianbundy** [comment]
Hmm, this is now crashing ssb-server for me.

```console
$ ssb-server start
ssb-server 15.0.1 /home/christianbundy/.ssb logging.level:notice
my key ID: +oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519
ssb-friends: stream legacy api used
Trace: deprecated api used: ssb-ref.parseAddress
    at Console.trace (internal/console/constructor.js:336:11)
    at Object.parseAddress (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-ref/index.js:96:15)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-local/index.js:55:22)
    at Socket.emit (events.js:193:13)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/broadcast-stream/index.js:51:12)
    at Socket.emit (events.js:193:13)
    at UDP.onMessage [as onmessage] (dgram.js:686:8)
/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-ooo/index.js:97
          if(!err) cb(null, value)
                   ^

TypeError: cb is not a function
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-ooo/index.js:97:20
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-db/create.js:63:9
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumeview-hashtable/index.js:99:11
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumeview-hashtable/multi.js:33:21
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumeview-hashtable/hashtable.js:50:17
    at Array.unboxerMap (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-db/minimal.js:85:35)
    at chainMaps (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/ssb-db/minimal.js:90:14)
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumedb/index.js:71:14
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumelog-offset/inject.js:89:9
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:48:11
```

```console
$ ssb-server get --private=true  %90awctn3YKZaod4teIGaNcRlvV5HHC8khb0aB6I2koU=.sha256

/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:125
      throw err
      ^

Error: stream ended with:0 but wanted:34
    at drain (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:43:26)
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:63:18
    at /home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:114:13
    at drain (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/christianbundy/.node_modules/lib/node_modules/ssb-server/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```
