### ISSUE TITLE
Error message when using ssb-server/plugins/locale

### ISSUE THREAD

**Issue by SyarifZapata** [ssbc/ssb-server#637]
I get following error messages when using ssb-server/plugins/local. I also have a question, how can i get the list of scuttlebot servers available in my local network. I tried `server.gossip.peers()` but it always return empty array. thanks

Trace: deprecated api used: ssb-ref.parseAddress
    at Object.parseAddress (/home/arkad/ssb-console/node_modules/ssb-server/node_modules/ssb-ref/index.js:96:15)
    at Socket.<anonymous> (/home/arkad/ssb-console/node_modules/ssb-server/plugins/local.js:55:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Socket.<anonymous> (/home/arkad/ssb-console/node_modules/ssb-server/node_modules/broadcast-stream/index.js:51:12)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
Trace: deprecated api used: ssb-ref.parseAddress
    at Object.parseAddress (/home/arkad/ssb-console/node_modules/ssb-ref/index.js:96:15)
    at Object.<anonymous> (/home/arkad/ssb-console/node_modules/ssb-gossip/index.js:236:26)
    at apply (/home/arkad/ssb-console/node_modules/muxrpc-validation/index.js:197:15)
    at Object.<anonymous> (/home/arkad/ssb-console/node_modules/muxrpc-validation/index.js:62:14)
    at Object.<anonymous> (/home/arkad/ssb-console/node_modules/scuttlebot-release/node_modules/secret-stack/util.js:80:17)
    at Object.<anonymous> (/home/arkad/ssb-console/node_modules/scuttlebot-release/node_modules/hoox/index.js:3:17)
    at Object.hooked [as add] (/home/arkad/ssb-console/node_modules/scuttlebot-release/node_modules/hoox/index.js:10:15)
    at Socket.<anonymous> (/home/arkad/ssb-console/node_modules/ssb-server/plugins/local.js:61:26)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)

**Comment by dominictarr** [comment]
that's not an error, it's just a deprecation notice. It's just logging because something we plan to refactor is being used. Once it gets annoying enough hopefully someone fixes the code so that thing isn't used anymore.
