### ISSUE TITLE
"Cannot read property 'match' of undefined" installing 14.1.4

### ISSUE THREAD

**Issue by qypea** [ssbc/ssb-server#641]
When trying to install ssb-server@14.1.4 I get the following error. Reading around online it appears that this is most often a corruption error in package-lock.json, usually due to an error during build. I can install 14.1.3 jut fine.

```
$ npm install -g --verbose ssb-server@14.1.4
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/home/q/.npm/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   '--verbose',
npm verb cli   'ssb-server@14.1.4' ]
npm info using npm@6.8.0
npm info using node@v8.10.0
npm verb npm-session 4a515fbe1f08234d
npm http fetch GET 200 https://registry.npmjs.org/ssb-server 26ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/ssb-server/-/ssb-server-14.1.4.tgz 152ms (from cache)
npm timing stage:loadCurrentTree Completed in 1820ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 12ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 361ms
npm timing stage:rollbackFailedOptional Completed in 34ms
npm timing stage:runTopLevelLifecycles Completed in 2394ms
npm verb stack TypeError: Cannot read property 'match' of undefined
npm verb stack     at tarballToVersion (/home/q/.npm/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
npm verb stack     at inflatableChild (/home/q/.npm/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
npm verb stack     at BB.each (/home/q/.npm/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
npm verb stack     at tryCatcher (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Object.gotValue (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
npm verb stack     at Object.gotAccum (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
npm verb stack     at Object.tryCatcher (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
npm verb stack     at _drainQueueStep (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm verb stack     at _drainQueue (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
npm verb stack     at Async._drainQueues (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
npm verb stack     at Immediate.Async.drainQueues (/home/q/.npm/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:794:20)
npm verb cwd /home/q
npm verb Linux 4.15.0-45-generic
npm verb argv "/usr/bin/node" "/home/q/.npm/bin/npm" "install" "-g" "--verbose" "ssb-server@14.1.4"
npm verb node v8.10.0
npm verb npm  v6.8.0
npm ERR! Cannot read property 'match' of undefined
npm verb exit [ 1, true ]
npm timing npm Completed in 2782ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/q/.npm/_logs/2019-03-01T13_35_11_129Z-debug.log
```
[2019-03-01T13_35_11_129Z-debug.log](https://github.com/ssbc/ssb-server/files/2919608/2019-03-01T13_35_11_129Z-debug.log)

**Comment by qypea** [comment]
@christianbundy I still have the same error when trying to install this morning. Has your fix been pushed to the npm repository?

**Comment by christianbundy** [comment]
Unfortunately it hasn't, we run integration tests with all of the plugins we use and apparently the tests for ssb-blobs and ssb-ooo are broken so it won't let me publish. I was able to merge one fix as https://github.com/ssbc/ssb-blobs/pull/13, but I can't merge https://github.com/dominictarr/ssb-ooo/pull/3 because it isn't in the SSBC organization (https://github.com/dominictarr/ssb-ooo/issues/2).

I was waiting to hear back from someone with push access to that repo, but I think I'll just have to `npm publish` and skip the tests so that we can unbreak ssb-server's installation.

**Comment by qypea** [comment]
Thanks. I can confirm it works for me now.
