### ISSUE TITLE
Can't connect to port 8008 when running inside docker container

### ISSUE THREAD

**Issue by timjrobinson** [ssbc/ssb-server#645]
I do most of my development inside docker containers. Recently ssb-server networking stopped working correctly when installing and running it globally inside a container. It starts correctly, and looks like it's working:

```
tim@9c5784b04f41:~$ ssb-server start 
ssb-server 14.1.6 /home/tim/.ssb logging.level:notice
my key ID: F7vk2EfOvstqrTz9AJhZ/bdENHeu/l/z15eMclJjAVw=.ed25519
WARNING-DEPRECATION: ssb-links not installed as a plugin. If you are using git-ssb, ssb-npm or patchfoo please consider installing it
ssb-friends: stream legacy api used
```

```
root@9c5784b04f41:/workspace# sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      9/node          
tcp6       0      0 :::8008                 :::*                    LISTEN      -               
tcp6       0      0 :::8989                 :::*                    LISTEN      -               
udp        0      0 0.0.0.0:8008            0.0.0.0:*                           -    
```

However when attempting to connect from inside the container it gives the following:

```
tim@9c5784b04f41:~$ sbot plugins.install ssb-about --verbose
Error: Could not connect to ssb-server :::8008
Use the "start" command to start it.
Use --verbose option to see full error
/home/tim/.nvm/versions/node/v10.15.3/lib/node_modules/ssb-server/bin.js:110
        if(config.verbose) throw err
                           ^
Error: could not connect to sbot
    at /home/tim/.nvm/versions/node/v10.15.3/lib/node_modules/ssb-server/node_modules/ssb-client/client.js:70:23
    at /home/tim/.nvm/versions/node/v10.15.3/lib/node_modules/ssb-server/node_modules/multiserver/compose.js:80:24
    at Socket.<anonymous> (/home/tim/.nvm/versions/node/v10.15.3/lib/node_modules/ssb-server/node_modules/multiserver/plugins/net.js:66:11)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  Error: connect EADDRNOTAVAIL :::8008 - Local (:::0)
    at internalConnect (net.js:872:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at defaultTriggerAsyncIdScope (net.js:962:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by timjrobinson** [comment]
So the reason for this occuring is it's not binding to the 0.0.0.0 interface. After adding the config file @ahdinosaur mentioned in https://github.com/ahdinosaur/ssb-pub/pull/20/files#diff-04c6e90faac2675aa89e2176d2eec7d8R76 it works correctly. 

This is the config file I'm using:

```
{
  "connections": {
    "incoming": {
      "net": [
        {
          "scope": "public",
          "host": "0.0.0.0",
          "external": [
            "ssb-test.internal"
          ],
          "transform": "shs",
          "port": 8008
        }
      ]
    },
    "outgoing": {
      "net": [
        {
          "transform": "shs"
        }
      ]
    }
  }
}
```

After doing this it binds to ip address 0.0.0.0 correctly:

```
root@9c5784b04f41:/workspace# sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8008            0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      9/node          
udp        0      0 0.0.0.0:8008            0.0.0.0:*                           -    
```

And commands work as expected:

```
tim@9c5784b04f41:/workspace/.ssb$ sbot plugins.install ssb-about --verbose                                                                  
Installing "ssb-about"...
+ ssb-about@2.0.0
added 25 packages from 13 contributors and audited 26 packages in 1.49s
found 0 vulnerabilities

"ssb-about" has been installed. Restart ssb-server to enable the plugin.
```
