### ISSUE TITLE
Error: cannot call:get, flumedb instance closed

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-server#660]
Looks like the ssb-ebt integration test is having issues:

https://api.travis-ci.org/v3/job/520977499/log.txt

```
Error: cannot call:get, flumedb instance closed
    at throwIfClosed (/home/travis/build/ssbc/ssb-server/node_modules/flumedb/wrap.js:11:28)
    at Object.get (/home/travis/build/ssbc/ssb-server/node_modules/flumedb/wrap.js:49:9)
    at EventEmitter.db.getVectorClock (/home/travis/build/ssbc/ssb-server/node_modules/ssb-db/create.js:144:13)
    at EventEmitter.hooked [as getVectorClock] (/home/travis/build/ssbc/ssb-server/node_modules/hoox/index.js:10:15)
    at Timeout._onTimeout (/home/travis/build/ssbc/ssb-server/node_modules/ssb-ebt/test/server.js:76:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
npm ERR! Test failed.  See above for more details.
```

cc: @dominictarr

**Comment by dominictarr** [comment]
okay, this should be fixed in ssb-ebt@5.6.2
