### ISSUE TITLE
Error: help command is missing from!

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-server#667]
When running Patchwork (ssb-server@14) with the new ssb-server@15 CLI it seems to just throw errors. Not sure how this should be resolved, but if the CLI is totally incompatible maybe we should tell people to upgrade their CLI to match the server version?

```console
$ ssb-server
at command: []
/home/christianbundy/src/ssbc/ssb-server/node_modules/muxrpcli/index.js:114
      throw new Error('help command is missing from!' + cmd.join('.'))
      ^

Error: help command is missing from!
    at usage (/home/christianbundy/src/ssbc/ssb-server/node_modules/muxrpcli/index.js:114:13)
    at next (/home/christianbundy/src/ssbc/ssb-server/node_modules/muxrpcli/index.js:186:7)
    at module.exports (/home/christianbundy/src/ssbc/ssb-server/node_modules/muxrpcli/index.js:151:5)
    at /home/christianbundy/src/ssbc/ssb-server/bin.js:159:5
    at /home/christianbundy/src/ssbc/ssb-server/node_modules/ssb-client/client.js:78:5
    at next (/home/christianbundy/src/ssbc/ssb-server/node_modules/multiserver/compose.js:28:14)
    at /home/christianbundy/src/ssbc/ssb-server/node_modules/multiserver/compose.js:34:9
    at _cb (/home/christianbundy/src/ssbc/ssb-server/node_modules/multiserver/plugins/shs.js:31:11)
    at /home/christianbundy/src/ssbc/ssb-server/node_modules/secret-handshake/protocol.js:122:7
    at Object.cb (/home/christianbundy/src/ssbc/ssb-server/node_modules/secret-handshake/protocol.js:57:11)
$ ssb-server --help
at command: []
/home/christianbundy/src/ssbc/ssb-server/node_modules/muxrpcli/index.js:114
      throw new Error('help command is missing from!' + cmd.join('.'))
      ^

Error: help command is missing from!
    at usage (/home/christianbundy/src/ssbc/ssb-server/node_modules/muxrpcli/index.js:114:13)
    at module.exports (/home/christianbundy/src/ssbc/ssb-server/node_modules/muxrpcli/index.js:131:29)
    at /home/christianbundy/src/ssbc/ssb-server/bin.js:159:5
    at /home/christianbundy/src/ssbc/ssb-server/node_modules/ssb-client/client.js:78:5
    at next (/home/christianbundy/src/ssbc/ssb-server/node_modules/multiserver/compose.js:28:14)
    at /home/christianbundy/src/ssbc/ssb-server/node_modules/multiserver/compose.js:34:9
    at _cb (/home/christianbundy/src/ssbc/ssb-server/node_modules/multiserver/plugins/shs.js:31:11)
    at /home/christianbundy/src/ssbc/ssb-server/node_modules/secret-handshake/protocol.js:122:7
    at Object.cb (/home/christianbundy/src/ssbc/ssb-server/node_modules/secret-handshake/protocol.js:57:11)
    at drain (/home/christianbundy/src/ssbc/ssb-server/node_modules/pull-reader/index.js:39:14)
$ ssb-server friends --help
at command: [ 'friends' ]
/home/christianbundy/src/ssbc/ssb-server/node_modules/muxrpcli/index.js:114
      throw new Error('help command is missing from!' + cmd.join('.'))
      ^

Error: help command is missing from!friends
    at usage (/home/christianbundy/src/ssbc/ssb-server/node_modules/muxrpcli/index.js:114:13)
    at module.exports (/home/christianbundy/src/ssbc/ssb-server/node_modules/muxrpcli/index.js:131:29)
    at /home/christianbundy/src/ssbc/ssb-server/bin.js:159:5
    at /home/christianbundy/src/ssbc/ssb-server/node_modules/ssb-client/client.js:78:5
    at next (/home/christianbundy/src/ssbc/ssb-server/node_modules/multiserver/compose.js:28:14)
    at /home/christianbundy/src/ssbc/ssb-server/node_modules/multiserver/compose.js:34:9
    at _cb (/home/christianbundy/src/ssbc/ssb-server/node_modules/multiserver/plugins/shs.js:31:11)
    at /home/christianbundy/src/ssbc/ssb-server/node_modules/secret-handshake/protocol.js:122:7
    at Object.cb (/home/christianbundy/src/ssbc/ssb-server/node_modules/secret-handshake/protocol.js:57:11)
    at drain (/home/christianbundy/src/ssbc/ssb-server/node_modules/pull-reader/index.js:39:14)
```

cc: @dominictarr

**Comment by dominictarr** [comment]
I am unable to reproduce this on my master, trying `npm install ssb-server -g` to see what happens

**Comment by christianbundy** [comment]
This doesn't occur when both the client and server are v15, it only happens when the client is v15 and the server is v14.

**Comment by dominictarr** [comment]
okay I fixed muxrpcli to throw a more helpful error if help is completely missing
