### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by luandro** [ssbc/ssb-server#672]
I've been trying to run `ssb-server start` and also been trying to call it on other libs, but on my normal ssb identity it throws a bunch of errors, similar to [Patchwork issue 1041](https://github.com/ssbc/patchwork/issues/1041):

```
  Error: past end:1173-779316470 < 648890483
    at Object.read (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:49:17)
    at next (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:47:16)
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:43:11
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:96:11
    at get (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:93:9)
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:41:16
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:96:11
    at get (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:93:9)
Error: view stream error, from:contacts2
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/flumedb/index.js:139:35
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/pull-stream/sinks/drain.js:20:24
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/pull-stream/throughs/async-map.js:28:19
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/pull-cursor/skip.js:12:26
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/pull-cursor/cursor.js:28:28
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/flumelog-offset/inject.js:42:22
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at Object.read (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:49:14)
  Error: past end:1173-779316470 < 648890483
    at Object.read (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:49:17)
    at next (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:47:16)
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:43:11
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:96:11
    at get (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:93:9)
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:41:16
    at /Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:96:11
    at get (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/Users/.nvm/versions/node/v8.13.0/lib/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:93:9)
console.js:116
      throw e;
      ^

RangeError: Maximum call stack size exceeded
    at process.nextTick (internal/process/next_tick.js:1:1)
    at onwrite (_stream_writable.js:453:15)
    at WriteStream.Socket._writeGeneric (net.js:789:5)
    at WriteStream.Socket._write (net.js:799:8)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at WriteStream.Writable.write (_stream_writable.js:290:11)
    at WriteStream.Socket.write (net.js:717:40)
    at write (console.js:111:12)
    at Console.warn (console.js:143:3)
```

I've tried doing a `npm ci` but hasn't solved. Strangely the ssb clients all work alright.

**Comment by luandro** [comment]
Maybe just some random error because of my `log.offset` file...

**Comment by clevinson** [comment]
@luandro I'm having this same issue.. Were you able to fix it by removing your `log.offset` ?
