### ISSUE TITLE
Error: plugin at:foo-identities expected name:foo-identities but had:foo

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-server#675]
Currently happening with all plugins installed with `ssb-server plugins.install`.

```
ssb-server 15.0.1 /home/christianbundy/.ssb logging.level:notice
my key ID: +oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU=.ed25519
/home/christianbundy/.config/yarn/global/node_modules/ssb-plugins/load-user-plugins.js:54
        throw new Error('plugin at:'+module_name+' expected name:'+name+' but had:'+(plugin||{}).name)
        ^

Error: plugin at:ssb-identities expected name:ssb-identities but had:identities
    at module.exports (/home/christianbundy/.config/yarn/global/node_modules/ssb-plugins/load-user-plugins.js:54:15)
    at Object.module.exports.loadUserPlugins (/home/christianbundy/.config/yarn/global/node_modules/ssb-plugins/index.js:240:55)
    at Object.<anonymous> (/home/christianbundy/.config/yarn/global/node_modules/ssb-server/bin.js:65:26)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by christianbundy** [comment]
Workaround is editing `~/.ssb/config` to hardcode `{ name: 'foo' }` manually.

**Comment by christianbundy** [comment]
cc: @dominictarr am I doing something wrong here? For example, `ssb-server plugins.install ssb-identities` sets the config as:

```json
{
  "plugins": {
    "ssb-identities": {
      "name": "ssb-identities"
    }
  }
}
```

which throws the above error. The fix is to manually change this to:

```json
{
  "plugins": {
    "ssb-identities": {
      "name": "identities"
    }
  }
}
```

**Comment by kode54** [comment]
I can't even install any plugins whatsoever due to this bug.
