### ISSUE TITLE
plugins.install: Cannot set property 'module' of undefined

### ISSUE THREAD

**Issue by xloem** [ssbc/ssb-server#677]
```
$ node bin.js plugins.install ssb-about

/shared/src/ssb-server/node_modules/muxrpcli/index.js:125
      throw err
      ^
TypeError: Cannot set property 'module' of undefined
    at Object.install (/shared/src/ssb-server/node_modules/ssb-plugins/index.js:117:23)
    at Object.hooked (/shared/src/ssb-server/node_modules/hoox/index.js:10:15)
    at Object.localCall (/shared/src/ssb-server/node_modules/muxrpc/local-api.js:31:29)
    at Object.<anonymous> (/shared/src/ssb-server/node_modules/muxrpc/local-api.js:37:22)
    at PacketStreamSubstream.stream.read (/shared/src/ssb-server/node_modules/muxrpc/stream.js:69:23)
    at PacketStream._onstream (/shared/src/ssb-server/node_modules/packet-stream/index.js:228:11)
    at PacketStream.write (/shared/src/ssb-server/node_modules/packet-stream/index.js:135:41)
    at /shared/src/ssb-server/node_modules/muxrpc/pull-weird.js:56:15
    at /shared/src/ssb-server/node_modules/pull-stream/sinks/drain.js:24:37
    at /shared/src/ssb-server/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
```

It looks like an interface has been changed on one end but not the other somewhere within the source.  Maybe package.json is not up-to-date?

**Comment by kris30pl** [comment]
https://github.com/ssbc/ssb-server/blob/4cc6f084e896be7a94c81a9fad86421f83e29dbd/.github/stale.yml#L1

**Comment by sbillig** [comment]
This works fine in v14.1.12, but is broken in v15+. Presumably broken by ssb-plugins that landed in v15.

**Comment by christianbundy** [comment]
See #675 for workarounds.
