### ISSUE TITLE
Cannot connect to running ssb-server

### ISSUE THREAD

**Issue by NiklasKunkel** [ssbc/ssb-server#681]
Installed the latest release (15.0.2) of ssb-server on Ubuntu 16.04.5 and it's running. However I can't seem to connect to the server.

```
>ssb-server/bin.js server >$HOME/logs/ssb-server.log &

>cat ssb-server.log 
WARNING-DEPRECATION: `sbot server` has been renamed to `ssb-server start`
ssb-server 15.0.2 /home/nkunkel/.ssb logging.level:notice
my key ID: SoGPH4un5Voz98oAZIbo4hYftc4slv4A+OHXPGCFHpA=.ed25519
ssb-friends: stream legacy api used

>ssb-server/bin.js whoami --verbose
Error: Could not connect to ssb-server 206.189.198.189:8008
Use the "start" command to start it.
Use --verbose option to see full error
/home/nkunkel/ssb-server/bin.js:105
        if(config.verbose) throw err
                           ^
Error: could not connect to sbot
    at /home/nkunkel/ssb-server/node_modules/ssb-client/client.js:70:23
    at next (/home/nkunkel/ssb-server/node_modules/multiserver/compose.js:24:14)
    at /home/nkunkel/ssb-server/node_modules/multiserver/compose.js:34:9
    at _cb (/home/nkunkel/ssb-server/node_modules/multiserver/plugins/shs.js:28:20)
    at /home/nkunkel/ssb-server/node_modules/secret-handshake/protocol.js:117:22
    at /home/nkunkel/ssb-server/node_modules/pull-handshake/index.js:10:5
    at /home/nkunkel/ssb-server/node_modules/pull-handshake/index.js:23:13
    at callback (/home/nkunkel/ssb-server/node_modules/pull-pushable/index.js:81:7)
    at drain (/home/nkunkel/ssb-server/node_modules/pull-pushable/index.js:68:39)
  Error: shs.client: server hung up when we sent hello (phase 3).
Possibly we dailed a wrong number, or the server does not wish to talk to us.
    at abort (/home/nkunkel/ssb-server/node_modules/secret-handshake/protocol.js:37:45)
    at Object.cb (/home/nkunkel/ssb-server/node_modules/secret-handshake/protocol.js:52:26)
    at drain (/home/nkunkel/ssb-server/node_modules/pull-reader/index.js:43:23)
  Error: stream ended with:64 but wanted:80
    at drain (/home/nkunkel/ssb-server/node_modules/pull-reader/index.js:43:26)
    at /home/nkunkel/ssb-server/node_modules/pull-reader/index.js:63:18
    at /home/nkunkel/ssb-server/node_modules/pull-reader/index.js:20:7
    at drain (/home/nkunkel/ssb-server/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/nkunkel/ssb-server/node_modules/stream-to-pull-stream/index.js:147:5)
    at Socket.emit (events.js:203:15)
    at TCP._handle.close (net.js:606:12)
```

**Comment by austinfrey** [comment]
@NiklasKunkel shot in the dark here, but what does resource usage look like using a tool like `htop`? i've run into this issue on some smaller resource machines when the server is under heavy load from indexing, it might just take awhile to settle down.

**Comment by NiklasKunkel** [comment]
It seems after a period of time it does allow me to connect to the server. Perhaps it's as you said and it was just busy indexing.
