### ISSUE TITLE
racecondition -- TypeError: Cannot read property 'client' of undefined

### ISSUE THREAD

**Issue by nichoth** [ssbc/ssb-server#692]
Sometimes it works, and sometimes it crashes. Any assistance is appreciated

https://github.com/nichoth/ssb-app/blob/92d9100a055fa49398aa895e1d6d36759c972220/test/server.js

```
 node test/server.js 
TAP version 13
# server
ok 1 should be truthy
# whoami
who { id: '@27SNA/j1hw/zhbWGoLX0A1UrEaM2Hxc7ei2e9dE/KnA=.ed25519' }
ok 2 whoami
# done
fallback to close
/Users/nick/code/ssb-app/node_modules/ssb-server/node_modules/secret-stack/core.js:223
          ms_client.client(coearseAddress(address), function (err, stream) {
                    ^

TypeError: Cannot read property 'client' of undefined
    at EventEmitter.connect (/Users/nick/code/ssb-app/node_modules/ssb-server/node_modules/secret-stack/core.js:223:21)
    at EventEmitter.hooked [as connect] (/Users/nick/code/ssb-app/node_modules/ssb-server/node_modules/hoox/index.js:10:15)
    at Object.connect (/Users/nick/code/ssb-app/node_modules/ssb-gossip/index.js:201:16)
    at /Users/nick/code/ssb-app/node_modules/ssb-gossip/schedule.js:136:16
    at Array.forEach (<anonymous>)
    at connect (/Users/nick/code/ssb-app/node_modules/ssb-gossip/schedule.js:135:8)
    at Timeout.<anonymous> (/Users/nick/code/ssb-app/node_modules/ssb-gossip/schedule.js:201:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at unrefdHandle (timers.js:520:7)
```

**Comment by staltz** [comment]
Seems like a legit issue, but likely related to secret-stack and ssb-gossip more than ssb-server.
