### ISSUE TITLE
macOS problems

### ISSUE THREAD

**Issue by TheKnarf** [ssbc/ssb-server#699]
```
sbot
error loading sodium bindings: Cannot find module 'sodium-native'
Require stack:
- /usr/local/lib/node_modules/ssb-server/node_modules/chloride/bindings.js
- /usr/local/lib/node_modules/ssb-server/node_modules/chloride/index.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-keys/index.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-config/defaults.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-config/inject.js
- /usr/local/lib/node_modules/ssb-server/bin.js
falling back to javascript version.
createLogStream|get|publish|add|status|progress|version|whoami|createHistoryStream
blobs # retrive, store, and share blobs
query # query ssb database with map-filter-reduce queries
search # full text search within ssb messages
```

```
sbot plugins.install ssb-npm-registry --from 'http://localhost:8989/blobs/get/&2afFvk14JEObC047kYmBLioDgMfHe2Eg5/gndSjPQ1Q=.sha256'
error loading sodium bindings: Cannot find module 'sodium-native'
Require stack:
- /usr/local/lib/node_modules/ssb-server/node_modules/chloride/bindings.js
- /usr/local/lib/node_modules/ssb-server/node_modules/chloride/index.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-keys/index.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-config/defaults.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-config/inject.js
- /usr/local/lib/node_modules/ssb-server/bin.js
falling back to javascript version.
/usr/local/lib/node_modules/ssb-server/node_modules/muxrpc-usage/index.js:9
  return o.commands
           ^

TypeError: Cannot read property 'commands' of undefined
    at isGroup (/usr/local/lib/node_modules/ssb-server/node_modules/muxrpc-usage/index.js:9:12)
    at get (/usr/local/lib/node_modules/ssb-server/node_modules/muxrpc-usage/index.js:14:8)
    at Object.exports.get (/usr/local/lib/node_modules/ssb-server/node_modules/muxrpc-usage/index.js:27:10)
    at output (/usr/local/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:45:17)
    at /usr/local/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:81:9
    at Object._requests.<computed> (/usr/local/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:38:5)
    at PacketStream._onrequest (/usr/local/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:151:26)
    at PacketStream.write (/usr/local/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:134:41)
    at /usr/local/lib/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:56:15
    at /usr/local/lib/node_modules/ssb-server/node_modules/pull-stream/sinks/drain.js:24:37
```

**Comment by markspanbroek** [comment]
The first error about sodium bindings is, as far as I know, just a warning. It tries to use the native compiled version of libsodium, but if it cannot find it it'll fall back to a javascript version. You can get rid of the warning by invoking `npm install -g sodium-native`.

I also suffer from the second error, and don't know how to solve that yet.

**Comment by markspanbroek** [comment]
I think the second issue is the same as described here: https://github.com/ssbc/patchwork/issues/610#issuecomment-388647395
