### ISSUE TITLE
Error when trying to accept invite

### ISSUE THREAD

**Issue by NiklasKunkel** [ssbc/ssb-server#700]
I'm using ssb-server 15.1.0

Trying to accept an invite from another peer running the same ssb version. 
Interfacing with ssb through the bash cli. I've scrambled the invite link for privacy

```
ssb-server invite.accept "137.43.174.21:8008:@EBH/a4krieoqkfhy2JJYChK+dYMkL//sBHqtk3dfqKE=.ed25519~oZlRjftyw9T7wCj4bTEPciDZbYrHqUOOfywgLjpVgB8="

/nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:123
      throw err
      ^
Error: invite not accepted
    at /nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/ssb-invite/index.js:257:31
    at Object._requests.(anonymous function) (/nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:38:5)
    at PacketStream._onrequest (/nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:151:26)
  Error: method:invite,use is not in list of allowed methods
    at Function.perms.pre (/nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/muxrpc/permissions.js:88:14)
    at Object.<anonymous> (/nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:35:21)
    at Object.request (/nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/muxrpc/stream.js:48:17)
    at PacketStream._onrequest (/nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:161:17)
    at PacketStream.write (/nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:134:41)
    at /nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:56:15
    at /nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/pull-stream/sinks/drain.js:24:37
    at /nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/nix/store/2mhfrggiwj34k7ja9n85ac2rsh82ybbn-node-ssb-server-15.1.0/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:39:14)
```

**Comment by NiklasKunkel** [comment]
Have had this happen on two separate machines now. Have been using this version for months now without issues and used this command at least a dozen times in the past week. Strange that it's popping up now.

**Comment by dominictarr** [comment]
this calls invite.accept on your local instance, which then uses the invite to call invite.use on the remote pub (which the invite is for) "method:invite,use is not in list of allowed methods" I think then means that this invite is invalid or you havn't authenticated to the pub or something like that, or the pub isn't running `ssb-invites` is it your pub? does it still do it with a new code?

**Comment by NiklasKunkel** [comment]
What are the conditions for an invite to be valid? Is there any state involved?

I've run into this issue numerous times now with different peers hosted in a variety of environments. Sometimes generating a new invite key on a peer is good enough to finally make it work. Other times, no matter how many invite keys I generated, they are never able to be accepted by some of my peers, but they can be accepted by other peers I own! Makes no sense to me. I can verify that ssb is running on the right ports with the right caps.

**Comment by dominictarr** [comment]
it's up to the pub that made it. They just store a state in their database to remember if it's been used or not. they have a counter of how many times they have been used.

it would help to know exactly what commands and code you are running. are you running the standard server code? or is your own code in there too?

**Comment by NiklasKunkel** [comment]
The invites are being generated by standard server code using the cli `ssb-server invite.create --limit 100` and accepted through `ssb-server invite.accept "$INVITE"`.

**Comment by dominictarr** [comment]
are you running the standard server code? or is your own code in there too?

**Comment by NiklasKunkel** [comment]
Standard server code.

**Comment by dominictarr** [comment]
@NiklasKunkel are you installing it via `npm install ssb-server -g` and then running `ssb-server start` or what are you doing?
