### ISSUE TITLE
Stream crash when creating invites for new pub

### ISSUE THREAD

**Issue by pospi** [ssbc/ssb-server#720]
Hiya (: I'm setting up a pub using Docker, following instructions at https://handbook.scuttlebutt.nz/guides/pubs/setup-a-pub

Setup and naming the pub all fine so far, but when I attempt to create invites I get this:

```
root@ssb:/# ssb-server invite.create 1000 --host ssb.spadgos.com
/usr/local/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:125
      throw err
      ^

Error: stream ended with:0 but wanted:34
    at drain (/usr/local/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:43:26)
    at /usr/local/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:63:18
    at /usr/local/lib/node_modules/ssb-server/node_modules/pull-reader/index.js:114:13
    at drain (/usr/local/lib/node_modules/ssb-server/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ssb-server/node_modules/stream-to-pull-stream/index.js:143:5)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Have tried just single invites rather than large numbers, no change to the error.

Using `ssb-server@15.2.0`; nodejs `v10.20.1`; Debian buster.

Weirdness encountered so far (in case relevant): because my hostname is bound to Cloudflare, the public IP of the box does not match the auto-discovered one even though I have it set correctly for Docker Compose. Thus I need to use the `--host` switch to make it resolve correctly.

**Comment by pospi** [comment]
Fixed this via advice from @christianbundy (: Issue was due to mixing positional and named arguments, which I did based on inference of the docs on the above Pub setup instructions.

Command I am now using is:

    ssb-server invite.create --uses 1000 --host ssb.spadgos.com

Would be good to have those docs updated to use the named arg format or include the host parameter in the invite creation example for consistency with the other commands on that page.

Still need to address some things but they are probably on my end and will follow up in `%xfaeGP6xK3d4wOThWbzhQ8izKDKXm1w1MjwqttjsDBQ=.sha256`.
