### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by clehner** [ssbc/ssb-server#734]

**Comment by timjrobinson** [comment]
I encountered this again today in local dev after pulling in a lot of new data. Indexing was stalling at 97% and the server wasn't fully booting and so wasn't responding to whoami. 

After updating ssb-db to the latest version `20.4.0` with `npm i -s ssb-db@latest` it seems to be indexing correctly and responding to commands again. 

I did get some new errors in server logs that I hadn't seen before, so maybe they were causing the stall before:

```
could not retrive msg: Error [NotFoundError]: Key not found in database [@/3q5HcRfJu6KYA+zRmpwPEB5EN5QF8Ia4xhCrCTHtxw=.ed25519,1]
    at /home/tim/projects/ssb-server/node_modules/levelup/lib/levelup.js:188:15
    at /home/tim/projects/ssb-server/node_modules/encoding-down/index.js:75:21
could not retrive msg: Error [NotFoundError]: Key not found in database [@+sPe2KX1gMaYAiQJKTtBNlFT2bhZOHW07G7n1h4As+w=.ed25519,1]
    at /home/tim/projects/ssb-server/node_modules/levelup/lib/levelup.js:188:15
    at /home/tim/projects/ssb-server/node_modules/encoding-down/index.js:75:21
```
