### ISSUE TITLE
Have an error on sbot start

### ISSUE THREAD

**Issue by cenyG** [ssbc/ssb-server#744]
Have this error on `sbot start`
````
internal/buffer.js:35............................. (indexes:0%)
    throw new ERR_OUT_OF_RANGE('value', `>= ${min} and <= ${max}`, value);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 4294967648
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32BE (internal/buffer.js:757:3)
    at Buffer.writeUInt32BE (internal/buffer.js:770:10)
    at Object.encode (/usr/lib/node_modules/ssb-server/node_modules/flumelog-offset/frame/offset-codecs.js:9:11)
    at Object.frame (/usr/lib/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:23:19)
    at /usr/lib/node_modules/ssb-server/node_modules/flumelog-offset/inject.js:19:26
    at Function.many.once (/usr/lib/node_modules/ssb-server/node_modules/obv/index.js:39:7)
    at /usr/lib/node_modules/ssb-server/node_modules/flumelog-offset/inject.js:15:11
    at drain (/usr/lib/node_modules/ssb-server/node_modules/append-batch/index.js:20:5)
    at Object.write [as append] (/usr/lib/node_modules/ssb-server/node_modules/append-batch/index.js:30:41)
````

**Comment by austinfrey** [comment]
@cenyG how large is the file `~/.ssb/log.offset`? the current default max size is `4294967295`
